export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="robbyrussell"
plugins=(git kubectl zsh-autosuggestions)

source $ZSH/oh-my-zsh.sh

alias ll="eza --icons=auto --git --long --octal-permissions"
alias cat="bat --theme=ansi"
alias kctx="kubectx"
alias kns="kubens"
alias vi='nvim'
alias vim='nvim'
alias python='python3'
