tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
tap "mas-cli/tap"

brew "mas"
brew "awscli"
brew "visual-studio-code"
brew "bat"
brew "exa"
brew "helm"
brew "htop"
brew "jq"
brew "k3d"
brew "k9s"
brew "kubernetes-cli"
brew "kube-ps1"
brew "kubectx"
brew "minikube"
brew "terraform"
brew "vault"
brew "zsh"
brew "zsh-completions"
brew "zsh-syntax-highlighting"
brew "lynx"
brew "tmux"
brew "pkg-config", link: true
brew "bash"
brew "git"

cask "font-dejavu-sans-mono-nerd-font"
cask "font-droid-sans-mono-nerd-font"
cask "font-fira-mono-nerd-font"
cask "font-inconsolata-go-nerd-font"
cask "font-meslo-lg-nerd-font"
cask "font-roboto-mono-nerd-font"
cask "multipass"
cask "firefox"
cask "google-chrome"
cask "slack"
cask "iterm2"
cask "bitwarden"
cask "spotify"

mas "com.apple.dt.Xcode", id: 497799835
