
import = []
live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
dynamic_padding = true
padding.x = 4 
padding.y = 4 
position.x = 0
position.y = 0
dimensions.columns = 190 
dimensions.lines = 55
decorations = "Buttonless"
opacity = 0.99
blur = true
option_as_alt = "None"
startup_mode = "Maximized"

[scrolling]
history = 10000
multiplier = 3

[font]
normal.family = "MesloLGS Nerd Font Mono"
normal.style = "Regular"
size = 12

[colors]
primary.foreground = "#00C601"

[cursor]
style = { shape = "Block", blinking = "Off" }
unfocused_hollow = true
thickness = 0.15

[mouse]
hide_when_typing = false

[shell]
program = "/bin/zsh"
args = ["-l"]

[selection]
save_to_clipboard = true

